### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joeflack4** [HOT-Ecosystem/tccm-model#4]
Need some proper docs.

Core components
- [x] 1. a very small concise README and a link to the docs generated using https://github.com/HOT-Ecosystem/tccm/issues/8.
- [x] 2. Don't spend time writing lots of material about history and vision. 
- [x] 3. concentrate on what the repo does.
- [x] 4. link to the slides harold presented (https://github.com/HOT-Ecosystem/tccm/issues/9)

It is is necessary to have a sentence to differentiating this repo from tccm-model however

Additional future topics:
1. API endpoints
2. About the model
3. About the multi-repository structure
4. History and vision

**Comment by cmungall** [comment]
there is an old migration guide I can dig out if it helps but I think it should be straightforward, just change the curie of the import

**Comment by joeflack4** [comment]
I know how to create a new LinkML repo from the template, but doing a migration, as you say, I'm not entirely sure about. If you think Harold might not know how, then you might want to link the migration guide here.

I set up a repo using the LinkML template, but "curie of the import" doesn't ring a bell.

**Comment by cmungall** [comment]
I made distinct tickets

 - #8 
 - #7 
 - #6 

For this issue, I would consider it done if you have a very small concise README and a link to the docs generated using #8. 

Don't spend time writing lots of material about history and vision. this may just confuse people. concentrate on what the repo does. Just link to the slides harold presented (#9)

It is is necessary to have a sentence to differentiating this repo from tccm-model however

**Comment by joeflack4** [comment]
@cmungall This is great. I'll work on this stuff. Thank you Chris.

**Comment by joeflack4** [comment]
@cmungall I updated the readme here as well as here: https://github.com/HOT-Ecosystem/tccm-model/

I added the steps you enumerated to the OP. However I don't know if they're really completed to satisfaction. I'd like to add more, honestly, but bandwidth (as well as background knowledge) is a little low. Feel free to re-open this issue as well as uncheck any of the boxes that you think weren't covered satisfactorily.

**Comment by joeflack4** [comment]
I also generated new github pages documentation via linkml-ws: https://hot-ecosystem.github.io/tccm/
