### ISSUE TITLE
Change schema to conform to linkml

### ISSUE THREAD

**Issue by cmungall** [HOT-Ecosystem/tccm-model#6]
This repo has a biolinkml schema

there is a migration guide here
https://github.com/linkml/linkml/blob/f08d32ff94451676b67ad006d90bd6305c060065/Migration.md

but I think it should be simple, just change the CURIE in the imports

**Comment by joeflack4** [comment]
@cmungall I think I made the correct change: https://github.com/HOT-Ecosystem/tccm/pull/10/commits/7a8413238380ed4dc0fd5e082ca3eb12133d0322

I added to this PR: #10 

These need to be regenerated in order for the update to be complete in rendered files, but I'm hesitant to do that righ tnow, as I don't think the directory / code structure will be finalized until @hsolbrig  reviews.
<img width="1285" alt="Screen Shot 2022-05-06 at 4 55 03 PM" src="https://user-images.githubusercontent.com/13045020/167215744-9d0e4b67-6945-454a-a9be-f89500aa17b2.png">

**Comment by cmungall** [comment]
Thanks!

**Comment by joeflack4** [comment]
Dang, you must have a long email backlog Chris! =P
