### ISSUE TITLE
use linkml-ws new to create a repo structure

### ISSUE THREAD

**Issue by cmungall** [HOT-Ecosystem/tccm-model#8]
See https://asciinema.org/a/GHydP2cs0NIyUdhjvwvSFvB91

you could run this "in place" OR it may be easier to simply make an entirely new repo and copy the contents from here to there

see also #7

**Comment by joeflack4** [comment]
@cmungall Thanks for the video instructions. I followed the instructions successfully.

@cmungall @hsolbrig However, I'm not sure where to move the contents of the old directory structure into the new. I think @hsolbrig would know better than I.

I created a new PR: https://github.com/HOT-Ecosystem/tccm/pull/10, if @hsolbrig can review, when you have time.

When I ran `linkml-ws`, I did so in a new dir `TEMP/tccm`. Then I made a commit.
<img width="229" alt="Screen Shot 2022-05-06 at 4 13 20 PM" src="https://user-images.githubusercontent.com/13045020/167210373-9dfbadca-7384-43bc-b6b2-51978885e0c9.png">

After that, I merged those contents into the root directory as well as I could, and made a PR.
